project:
  type: website
  output-dir: docs

website:
  title: "Mohammed Yusuf Shaikh"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Projects
        href: projects.qmd
      - text: Resume
        href: Resume.pdf
    right: 
      - about.qmd
      - icon: github
        href: https://yusuf365.github.io/My-Portfolio.github.io/

format:
  html:
    theme: solar
    css: styles.css
    toc: true



