<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>simulation-spca-sta315-project – Mohammed Yusuf Shaikh</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a class="navbar-brand" href="../index.html">
    <span class="navbar-title">Mohammed Yusuf Shaikh</span>
    </a>
  </div>
            <div id="quarto-search" class="" title="Search"></div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" role="menu" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../index.html"> 
<span class="menu-text">Home</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../projects.html"> 
<span class="menu-text">Projects</span></a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../Mohammed_Yusuf_Shaikh_Resume_Porfolio.pdf"> 
<span class="menu-text">Resume</span></a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item">
    <a class="nav-link" href="../about.html"> 
<span class="menu-text">About me</span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://yusuf365.github.io/My-Portfolio.github.io/"> <i class="bi bi-github" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="mailto:mohammedyusuf.shaikh@mail.utoronto.ca"> <i class="bi bi-envelope" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/mohammed-yusuf-shaikh-5b564323b"> <i class="bi bi-linkedin" role="img">
</i> 
<span class="menu-text"></span></a>
  </li>  
</ul>
          </div> <!-- /navcollapse -->
            <div class="quarto-navbar-tools">
</div>
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#sec-1" id="toc-sec-1" class="nav-link active" data-scroll-target="#sec-1"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#sec-2" id="toc-sec-2" class="nav-link" data-scroll-target="#sec-2"><span class="header-section-number">2</span> Why is there a need for Sparse PCA</a></li>
  <li><a href="#motivation-algorithm-for-spca" id="toc-motivation-algorithm-for-spca" class="nav-link" data-scroll-target="#motivation-algorithm-for-spca"><span class="header-section-number">3</span> Motivation &amp; Algorithm for SPCA</a></li>
  <li><a href="#sec-3" id="toc-sec-3" class="nav-link" data-scroll-target="#sec-3"><span class="header-section-number">4</span> Simulation Procedure</a>
  <ul class="collapse">
  <li><a href="#generating-data" id="toc-generating-data" class="nav-link" data-scroll-target="#generating-data"><span class="header-section-number">4.1</span> Generating Data</a></li>
  <li><a href="#principal-component-analysis" id="toc-principal-component-analysis" class="nav-link" data-scroll-target="#principal-component-analysis"><span class="header-section-number">4.2</span> Principal Component Analysis</a></li>
  <li><a href="#sparse-principal-component-analysis" id="toc-sparse-principal-component-analysis" class="nav-link" data-scroll-target="#sparse-principal-component-analysis"><span class="header-section-number">4.3</span> Sparse Principal Component Analysis</a></li>
  <li><a href="#results" id="toc-results" class="nav-link" data-scroll-target="#results"><span class="header-section-number">4.4</span> Results</a></li>
  </ul></li>
  <li><a href="#sec-4" id="toc-sec-4" class="nav-link" data-scroll-target="#sec-4"><span class="header-section-number">5</span> Conclusion</a></li>
  <li><a href="#sec-5" id="toc-sec-5" class="nav-link" data-scroll-target="#sec-5"><span class="header-section-number">6</span> Appendix</a></li>
  <li><a href="#sec-6" id="toc-sec-6" class="nav-link" data-scroll-target="#sec-6"><span class="header-section-number">7</span> References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="Simulation-spca-STA315-Project.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">




<section id="sec-1" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>Principal Component Analysis (PCA) a method we know is used as statistical technique to reduce the dimensionality of data. PCA Methods strategically aims to find a “good” linear combination of <span class="math inline">\(X1,.....,X_p\)</span> such that the linear combination explains the most variability or randomness present in the dataset.</p>
<p>Mathematically, each <span class="math inline">\(i\)</span>-th principal component is a linear combination of the original features:</p>
<p><span class="math display">\[
Y_i = \boldsymbol{\ell}_i^\top \mathbf{X}
\]</span></p>
<p>Where,</p>
<ul>
<li><p><span class="math inline">\(Y_i \text{ is the } i\text{-th principal component}\)</span></p></li>
<li><p><span class="math inline">\(\mathbf{X} = (X_1, X_2, \ldots, X_p)^\top \text{ is the vector of original features}\)</span></p></li>
<li><p><span class="math inline">\(\boldsymbol{\ell}_i = (\ell_{i1}, \ell_{i2}, \ldots, \ell_{ip})^\top \text{ is the loading vector (weights)}\)</span></p></li>
</ul>
<p>The paper discusses that PCA method uses Singular Value Decomposition (SVD) to compute principal components, where X is a standardized data matrix. The X data matrix can be broken down to <span class="math inline">\(Z=UD\)</span> which represnet principal component and matrix <span class="math inline">\(V\)</span> are the loadings that explain how much each original variable contributes to each principal component.</p>
<p><span class="math display">\[ X = UDV^T\]</span></p>
<ul>
<li><p><span class="math inline">\(U \text{ contains the Eigenvectors }\)</span></p></li>
<li><p><span class="math inline">\(D \text{ contains the Eigenvalues }\)</span></p></li>
</ul>
<p>Although in PCA method the components capture maximum variance and compresses data while retaining important information despite that we have a larger drawback that is PCA uses all the variables when creating each principal components as a result the PC ends up being a mixture of every variable making it harder to interpret therefore lack of sparsity implies PCA doesn’t do variable selection. Moreover, the loadings are usually nonzero, making it hard to interpret which variables that are truly important and contribute to principal component.</p>
<p>To overcome the limitation of the PCA, a paper was presented by Hui Zou, Trevor Hastie, and Robert Tibshirani(2006). The paper <span class="citation" data-cites="rSpca">(<a href="#ref-rSpca" role="doc-biblioref">Zou, Hastie, and Tibshirani 2006</a>)</span> introduces a new method called Sparse Principal Component Analysis (SPCA). The idea focused on to make PCA a more interpretable method by forcing some of the loadings to be exactly zero. This paper presents a detailed review of SPCA, explains its methodology, compares it with existing alternatives, and reproduces a key simulation study from the original paper.</p>
</section>
<section id="sec-2" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Why is there a need for Sparse PCA</h1>
<p>According to PCA Method the loading vector contains non-zero values for all p variables meaning every variable contributes to each component. This makes interpretation difficult. This is a major problem when p variables are large in number. For example in gene expression data with 10,000 genes features, the principal component are influenced by all genes which hinders the ability to extract meaningful interpretation. Sparsity aims at to having many zero entries in a vector. In terms of PCA, sparse loadings implies that only a few variables significantly contribute to each component. The Sparse Principal component Analysis produces principal components with sparse loading which implies many coefficients are set to zero and making PC more interpretable.</p>
<p>The authors discusses earlier attempts to use sparsity in PCA method like SCotLASS (Sparse Component Technique using LASSO) method that used tuning parameter t, and when sufficiently t is small it forces some loading to be exactly 0. But one of the major drawback was that there was no clear method to determine an optimal <strong>t</strong> and it failed to produce sufficiently sparse loadings while maintaining a high percentage of explained variance.</p>
</section>
<section id="motivation-algorithm-for-spca" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Motivation &amp; Algorithm for SPCA</h1>
<p>The limitations encouraged the authors to produce an optimal algorithm, which involved recasting PCA as a ridge regression problem and they added lasso penalty to produce sparse loading. The equation is the Elastic Net Regression where we fit the sparse loadings which is given by: <span class="math display">\[
\arg\min_{A, B} \sum_{i=1}^{n} \left\| \mathbf{x}_i - AB^T \mathbf{x}_i \right\|^2 + \lambda \sum_{j=1}^{k} \left\| \beta_j \right\|^2 + \sum_{j=1}^{k} \lambda_{1,j} \left\| \beta_j \right\|_1
\]</span> This is the alternating minimization algorithm is to minimize the SPCA criterion which is available from <strong>elasticnet</strong> package as function <strong>spca()</strong>. To begin with we find principal component using PCA method and we take only few PC which explain majority of variances. We call the loading vectors as matrix A. With fixed matrix A we solve the elastic net problem to get matrix B to find sparse loading matrix. Nextly we fix matrix B and solve for matrix A and we repeat the steps until the net elastic regression converges. Hence in SPCA result in column matrix B which tells what variables are important for each principal component.</p>
</section>
<section id="sec-3" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Simulation Procedure</h1>
<p>We simulate a Synthetic dataset based on paper Sparse Principal Component Analysis (SPCA) give by Hui Zou, Trevor Hastie, and Robert Tibshirani(2006). The aim of the simulation is to evaluate how well classic PCA and Sparse Principal Component Analysis (SPCA) perform on synthetic example that has three hidden factors. We will reproduce the same result as presented in paper by authors. We use R Package for fitting the SPCA model (and elastic net models) which is available under <strong>elasticnet</strong> package created by the authors.</p>
<p>The simulated data reproduced we used the programming language R <span class="citation" data-cites="R">(<a href="#ref-R" role="doc-biblioref">R Core Team 2022</a>)</span> with support of additional packages in R: ‘tidyverse’ <span class="citation" data-cites="rTidyverse">(<a href="#ref-rTidyverse" role="doc-biblioref">Wickham et al. 2019</a>)</span>, ‘dplyr’ <span class="citation" data-cites="rDplyr">(<a href="#ref-rDplyr" role="doc-biblioref">Wickham et al. 2022</a>)</span>, ‘elasticnet’ <span class="citation" data-cites="relasticnet">(<a href="#ref-relasticnet" role="doc-biblioref">Zou and Hastie 2020</a>)</span>, ‘knitr’ <span class="citation" data-cites="rKnitr">(<a href="#ref-rKnitr" role="doc-biblioref">Xie 2014</a>)</span>, ‘PCA’ <span class="citation" data-cites="rPCA">(<a href="#ref-rPCA" role="doc-biblioref">Verzani 2022</a>)</span>, ‘scale function’ <span class="citation" data-cites="rscalefunction">(<a href="#ref-rscalefunction" role="doc-biblioref">R-bloggers 2021</a>)</span>. We also utilized ‘Applications in R’ <span class="citation" data-cites="ralexandertellingstorieswithdata">(<a href="#ref-ralexandertellingstorieswithdata" role="doc-biblioref">Alexander 2023</a>)</span></p>
<section id="generating-data" class="level2" data-number="4.1">
<h2 data-number="4.1" class="anchored" data-anchor-id="generating-data"><span class="header-section-number">4.1</span> Generating Data</h2>
<p>For generating data we used 10 observable variables(<em>p</em>) <span class="math inline">\(X_1,.....X_{10}\)</span>. Number of variables are used as standard as per given in the paper procedures and we simulate 100 observation for each variable. For the next part we define 3 hidden variables - latent factors based on authors paper which imples the factors that influence observed variables.</p>
<p><span class="math display">\[
V_1 \sim \mathcal{N}(0, 290)
\]</span></p>
<p><span class="math display">\[
V_2 \sim \mathcal{N}(0, 300)
\]</span></p>
<p>The variables <span class="math inline">\(V_1\)</span>, <span class="math inline">\(V_2\)</span> and <span class="math inline">\(V_3\)</span> are 3 underlying <em>hidden</em> factors that govern th observed variables. The factors <span class="math inline">\(V_1\)</span> &amp; <span class="math inline">\(V_2\)</span> are independent variables with high variances, whereas <span class="math inline">\(V_3\)</span> is a linear combination of factors <span class="math inline">\(V_1\)</span> &amp; <span class="math inline">\(V_2\)</span> and equation is given by:</p>
<p><span class="math display">\[
V_3 = -0.3 V_1 + 0.925 V_2 + \epsilon, \quad \text{where } \epsilon \sim \mathcal{N}(0, 1)
\]</span></p>
<p><span class="math display">\[
V_3 \sim \mathcal{N}(0, 283.8)
\]</span></p>
<p>It is given that <span class="math inline">\(V_1\)</span> &amp; <span class="math inline">\(V_2\)</span> and <span class="math inline">\(\epsilon\)</span> are mutually independent of each other.<span class="math inline">\(V_3\)</span> being the linear combination of <span class="math inline">\(V_1\)</span> &amp; <span class="math inline">\(V_2\)</span> we find the mean and variance of <span class="math inline">\(V_3\)</span>. The calculation is provided in the Appendix. We constructed an exact covariance matrix of <span class="math inline">\(X_1,.....,X_{10}\)</span> variables and each variables from <span class="math inline">\(X_1\)</span> to <span class="math inline">\(X_4\)</span> is constructed as:</p>
<p><span class="math display">\[
X_i = V_1 + \epsilon_i, \quad \text{where } \epsilon_{ij} \sim \mathcal{N}(0, 1) \quad \text{for } i = 1, 2, 3, 4
\]</span> <span class="math display">\[
X_i = V_2 + \epsilon_i, \quad \text{where } \epsilon_{ij} \sim \mathcal{N}(0, 1) \quad \text{for } i = 5, 6, 7, 8
\]</span> <span class="math display">\[
X_i = V_3 + \epsilon_i, \quad \text{where } \epsilon_{ij} \sim \mathcal{N}(0, 1) \quad \text{for } i = 9, 10
\]</span></p>
<p>where <span class="math inline">\(\epsilon_{ij}\)</span> is an independent Gaussian noise and <span class="math inline">\(j \in \{1, 2, 3\}\)</span> that indicates which latent factor group the variable belongs to. So, similarly for variables from <span class="math inline">\(X_5\)</span> to <span class="math inline">\(X_8\)</span> depend on <span class="math inline">\(V_2\)</span> and variables <span class="math inline">\(X_9\)</span> &amp; <span class="math inline">\(X_{10}\)</span> depends on <span class="math inline">\(V_3\)</span>. In our simulation, we get <em>n</em> = 100 observations for each of the 10 variables, resulting in a data matrix of size 10 × 100.</p>
<p>Before applying dimension reduction methods, on our simulated data matrix X, we standardized it so that each variable had mean zero and unit variance using <strong>scale</strong> which is a generic function whose default method centers the columns of a matrix. Standardization ensures that all variables contribute equally when performing principal component analysis (PCA) or Sparse PCA. Note that we do not proceed with SCoTLASS or Simple Thresholding method under simulation as our key interest only remains in PCA and SPCA method.</p>
</section>
<section id="principal-component-analysis" class="level2" data-number="4.2">
<h2 data-number="4.2" class="anchored" data-anchor-id="principal-component-analysis"><span class="header-section-number">4.2</span> Principal Component Analysis</h2>
<p>We first applied Principal Component Analysis using the <strong>‘prcomp()’</strong> function in R on our standardized dataset. It computes the principal components from the data matrix using Singular Value Decomposition (SVD) method as discussed in above methodology. This is generally the preferred method for numerical accuracy for obtaining stable principal components. We extracted the loading for the first three principal components, and we computed the proportion of variance explained by the first, second and third PCs using the standard PCA output. These loading and variances summarize how much of the variability in the data is captured by the principal components from <a href="#tbl-pca-spca-loadings" class="quarto-xref">Table&nbsp;1</a>.</p>
</section>
<section id="sparse-principal-component-analysis" class="level2" data-number="4.3">
<h2 data-number="4.3" class="anchored" data-anchor-id="sparse-principal-component-analysis"><span class="header-section-number">4.3</span> Sparse Principal Component Analysis</h2>
<p>Moving on from Principal component analysis, we apply Sparse PCA using <strong>spca()</strong> function from <strong>elasticnet</strong> package. The formula takes the input of standardized data matrix, with K = 2 that computes first 2 components i.e.&nbsp;PC1 and PC2, we impose sparsity by specifying that each component should have exactly four non-zero loading (sparse = “varnum”, para = c(4,4)) in the simulation design with lambda set to standard default value of 1e-6.</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code>You may wish to restart and use a more efficient way 
let the argument x be the sample covariance/correlation matrix and set type=Gram </code></pre>
</div>
<div id="tbl-pca-spca-loadings" class="cell quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pca-spca-loadings-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: The results from PCA and SPCA Loadings
</figcaption>
<div aria-describedby="tbl-pca-spca-loadings-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">PCA PC1</th>
<th style="text-align: right;">PCA PC2</th>
<th style="text-align: right;">PCA PC3</th>
<th style="text-align: right;">SPCA PC1</th>
<th style="text-align: right;">SPCA PC2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">X1</td>
<td style="text-align: right;">0.118</td>
<td style="text-align: right;">-0.478</td>
<td style="text-align: right;">0.085</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">-0.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">X2</td>
<td style="text-align: right;">0.118</td>
<td style="text-align: right;">-0.478</td>
<td style="text-align: right;">0.092</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">-0.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">X3</td>
<td style="text-align: right;">0.117</td>
<td style="text-align: right;">-0.478</td>
<td style="text-align: right;">0.095</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">-0.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">X4</td>
<td style="text-align: right;">0.118</td>
<td style="text-align: right;">-0.478</td>
<td style="text-align: right;">0.078</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">-0.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">X5</td>
<td style="text-align: right;">-0.391</td>
<td style="text-align: right;">-0.146</td>
<td style="text-align: right;">-0.266</td>
<td style="text-align: right;">-0.5</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">X6</td>
<td style="text-align: right;">-0.391</td>
<td style="text-align: right;">-0.146</td>
<td style="text-align: right;">-0.263</td>
<td style="text-align: right;">-0.5</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">X7</td>
<td style="text-align: right;">-0.391</td>
<td style="text-align: right;">-0.146</td>
<td style="text-align: right;">-0.274</td>
<td style="text-align: right;">-0.5</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">X8</td>
<td style="text-align: right;">-0.391</td>
<td style="text-align: right;">-0.147</td>
<td style="text-align: right;">-0.298</td>
<td style="text-align: right;">-0.4</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">X9</td>
<td style="text-align: right;">-0.409</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: right;">0.573</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">X10</td>
<td style="text-align: right;">-0.409</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: right;">0.580</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Explained Variance (%)</td>
<td style="text-align: right;">59.700</td>
<td style="text-align: right;">40.000</td>
<td style="text-align: right;">0.080</td>
<td style="text-align: right;">39.6</td>
<td style="text-align: right;">39.8</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Later on, we obtain percentage of variance explained by each principal component that is obtained using the <strong>summary()</strong> function on the PCA object and it is extracted for PC1, PC2 &amp; PC3. Similarly we compute percentage of variance explained for SPCA; given by <em>pev</em> output from spca function. The result are presented in <a href="#tbl-pca-spca-loadings" class="quarto-xref">Table&nbsp;1</a> with first 10 rows showing the PCA and SPCA loadings for each variable. The last row of table summarizes the percentage of explained variances for the first three principal components under PCA method and the first two sparse principal components under SPCA method.</p>
</section>
<section id="results" class="level2" data-number="4.4">
<h2 data-number="4.4" class="anchored" data-anchor-id="results"><span class="header-section-number">4.4</span> Results</h2>
<p>The simulation result align closely with the results from thr paper presented by authors Hui Zou, Trevor Hastie, and Robert Tibshirani (2006). The result from first to PCs from PCA method catpture maximum total variance of 99.7% (PC1 explains 59.7% and PC2 explains 40%) which ideally shed the light upon the fact the simulated dataset is dominated by variables <span class="math inline">\(V_1\)</span> and <span class="math inline">\(V_2\)</span>. Also, the loading values in <a href="#tbl-pca-spca-loadings" class="quarto-xref">Table&nbsp;1</a> all behave similarly with Synthetic Example. The magnitude showcases that PC1 captures variability related to latent factors <span class="math inline">\(V_2\)</span> using <span class="math inline">\(X_5, X_6, X_7, X_8\)</span> variables as they have large loading values of -0.391. On the other hand, variables <span class="math inline">\(X_1, X_2, X_3, X_4\)</span> show loadings of -0.478 on PC2 corresponding to latent factor <span class="math inline">\(V_1\)</span>.</p>
<p>For SPCA loading values observe from <a href="#tbl-pca-spca-loadings" class="quarto-xref">Table&nbsp;1</a> that the method selects only important variables and forces other variable to be set to zero. Hence in the simulation we produce ideal sparse PCs. Note we did not use adjusted variance. The SPCA loadings match th simulation setup almost exactly The magnitude showcases that PC1 captures variability related to latent factor V2 using <span class="math inline">\(X_5, X_6, X_7, X_8\)</span> variables as they have large loading values of -0.5 On the other hand, variables <span class="math inline">\(X_1, X_2, X_3, X_4\)</span> show strong loadings of -0.5 on PC2 corresponding to latent factor <span class="math inline">\(V_1\)</span>. To conclude with SPCA primarily focus on most important variables while still explaining high variance of 79.4% and also notice it is easy to interpret the key variables being highlighted as important.</p>
</section>
</section>
<section id="sec-4" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Conclusion</h1>
<p>To conclude with, in this paper we explored principal component analysis method and its limitation. To mitigate the limitation we show SPCA which showcased sparsity by forcing loading variables to be set to zero. We provide SCPA methodology explanation of the algorithm followed by reproducing a simulation example presented by the paper <span class="citation" data-cites="rSpca">(<a href="#ref-rSpca" role="doc-biblioref">Zou, Hastie, and Tibshirani 2006</a>)</span>. The Table results compares PCA and SPCA principal components as well as explained variances. In conclusion SPCA provides a powerful alternative to PCA for analyzing high dimensional dataset.</p>
<div style="page-break-after: always;"></div>
</section>
<section id="sec-5" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Appendix</h1>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Readme</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co"># - Make sure you load necessary packages </span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="co"># - store reference.bib file in same folder to render pdf with references</span></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="co"># Load necessary package</span></span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("elasticnet")</span></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("janitor")</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("dplyr")</span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("knitr")</span></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co"># install.packages("tidyverse")</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Load Libraries</span></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(elasticnet)</span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(dplyr)</span>
<span id="cb2-15"><a href="#cb2-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(janitor)</span>
<span id="cb2-16"><a href="#cb2-16" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(knitr)</span>
<span id="cb2-17"><a href="#cb2-17" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb2-18"><a href="#cb2-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-19"><a href="#cb2-19" aria-hidden="true" tabindex="-1"></a><span class="co"># Using seed to get same reproducible result </span></span>
<span id="cb2-20"><a href="#cb2-20" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">123</span>) </span>
<span id="cb2-21"><a href="#cb2-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-22"><a href="#cb2-22" aria-hidden="true" tabindex="-1"></a><span class="co"># Generating Data</span></span>
<span id="cb2-23"><a href="#cb2-23" aria-hidden="true" tabindex="-1"></a><span class="co"># no. of observations we went through multiple trial &amp; errors for value of n for high dimensionality</span></span>
<span id="cb2-24"><a href="#cb2-24" aria-hidden="true" tabindex="-1"></a>n <span class="ot">&lt;-</span> <span class="dv">10000</span></span>
<span id="cb2-25"><a href="#cb2-25" aria-hidden="true" tabindex="-1"></a><span class="co"># no. of variable/features (predictors) we use for synthetic example</span></span>
<span id="cb2-26"><a href="#cb2-26" aria-hidden="true" tabindex="-1"></a>p <span class="ot">&lt;-</span> <span class="dv">10</span></span>
<span id="cb2-27"><a href="#cb2-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-28"><a href="#cb2-28" aria-hidden="true" tabindex="-1"></a><span class="co"># Specifing Three latent variables - hidden factors as per paper Synthetic example</span></span>
<span id="cb2-29"><a href="#cb2-29" aria-hidden="true" tabindex="-1"></a>V1 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="fu">sqrt</span>(<span class="dv">290</span>))  </span>
<span id="cb2-30"><a href="#cb2-30" aria-hidden="true" tabindex="-1"></a>V2 <span class="ot">&lt;-</span> <span class="fu">rnorm</span>(n, <span class="at">mean =</span> <span class="dv">0</span>, <span class="at">sd =</span> <span class="fu">sqrt</span>(<span class="dv">300</span>))  </span>
<span id="cb2-31"><a href="#cb2-31" aria-hidden="true" tabindex="-1"></a>V3 <span class="ot">&lt;-</span> <span class="sc">-</span><span class="fl">0.3</span> <span class="sc">*</span> V1 <span class="sc">+</span> <span class="fl">0.925</span> <span class="sc">*</span> V2 <span class="sc">+</span> <span class="fu">rnorm</span>(n)</span>
<span id="cb2-32"><a href="#cb2-32" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-33"><a href="#cb2-33" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-34"><a href="#cb2-34" aria-hidden="true" tabindex="-1"></a><span class="co"># Generating Matrix as per synthetic example</span></span>
<span id="cb2-35"><a href="#cb2-35" aria-hidden="true" tabindex="-1"></a>X <span class="ot">&lt;-</span> <span class="fu">matrix</span>(<span class="dv">0</span>, <span class="at">nrow =</span> n, <span class="at">ncol =</span> p)</span>
<span id="cb2-36"><a href="#cb2-36" aria-hidden="true" tabindex="-1"></a>X[, <span class="dv">1</span><span class="sc">:</span><span class="dv">4</span>]  <span class="ot">&lt;-</span> V1 <span class="sc">+</span> <span class="fu">matrix</span>(<span class="fu">rnorm</span>(n <span class="sc">*</span> <span class="dv">4</span>), <span class="at">nrow =</span> n)</span>
<span id="cb2-37"><a href="#cb2-37" aria-hidden="true" tabindex="-1"></a>X[, <span class="dv">5</span><span class="sc">:</span><span class="dv">8</span>]  <span class="ot">&lt;-</span> V2 <span class="sc">+</span> <span class="fu">matrix</span>(<span class="fu">rnorm</span>(n <span class="sc">*</span> <span class="dv">4</span>), <span class="at">nrow =</span> n)</span>
<span id="cb2-38"><a href="#cb2-38" aria-hidden="true" tabindex="-1"></a>X[, <span class="dv">9</span><span class="sc">:</span><span class="dv">10</span>] <span class="ot">&lt;-</span> V3 <span class="sc">+</span> <span class="fu">matrix</span>(<span class="fu">rnorm</span>(n <span class="sc">*</span> <span class="dv">2</span>), <span class="at">nrow =</span> n)</span>
<span id="cb2-39"><a href="#cb2-39" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-40"><a href="#cb2-40" aria-hidden="true" tabindex="-1"></a><span class="co"># We standardize the data matrix as it is required for PCA and SPCA method</span></span>
<span id="cb2-41"><a href="#cb2-41" aria-hidden="true" tabindex="-1"></a>X_standardized <span class="ot">&lt;-</span> <span class="fu">scale</span>(X, <span class="at">center =</span> <span class="cn">TRUE</span>, <span class="at">scale =</span> <span class="cn">TRUE</span>)</span>
<span id="cb2-42"><a href="#cb2-42" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-43"><a href="#cb2-43" aria-hidden="true" tabindex="-1"></a><span class="co"># PCA Method</span></span>
<span id="cb2-44"><a href="#cb2-44" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-45"><a href="#cb2-45" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply PCA Method to standardized data prcomp() is used </span></span>
<span id="cb2-46"><a href="#cb2-46" aria-hidden="true" tabindex="-1"></a>pca_loading_value <span class="ot">&lt;-</span> <span class="fu">prcomp</span>(X_standardized)</span>
<span id="cb2-47"><a href="#cb2-47" aria-hidden="true" tabindex="-1"></a><span class="co"># We round the loading values for PC1, PC2 &amp; PC3 but we extract it before using $rotation</span></span>
<span id="cb2-48"><a href="#cb2-48" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">round</span>(pca_loading_value<span class="sc">$</span>rotation[, <span class="dv">1</span><span class="sc">:</span><span class="dv">3</span>], <span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>         PC1    PC2    PC3
 [1,]  0.118 -0.478  0.085
 [2,]  0.118 -0.478  0.092
 [3,]  0.117 -0.478  0.095
 [4,]  0.118 -0.478  0.078
 [5,] -0.391 -0.146 -0.266
 [6,] -0.391 -0.146 -0.263
 [7,] -0.391 -0.146 -0.274
 [8,] -0.391 -0.147 -0.298
 [9,] -0.409  0.005  0.573
[10,] -0.409  0.005  0.580</code></pre>
</div>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Total variance is explained by PCA</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>total_explained_variance <span class="ot">&lt;-</span> <span class="fu">summary</span>(pca_loading_value)<span class="sc">$</span>importance[<span class="st">"Proportion of Variance"</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">2</span>] <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Sparse PCA Method</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Apply Sparse PCA Method to standardized data spca() is used from elastic net package</span></span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a>spca_result <span class="ot">&lt;-</span> <span class="fu">spca</span>(X_standardized, <span class="at">K =</span> <span class="dv">2</span>, <span class="at">type =</span> <span class="st">"predictor"</span>, <span class="at">sparse =</span> <span class="st">"varnum"</span>, <span class="at">para =</span> <span class="fu">c</span>(<span class="dv">4</span>, <span class="dv">4</span>), <span class="at">lambda =</span> <span class="fl">1e-6</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>You may wish to restart and use a more efficient way 
let the argument x be the sample covariance/correlation matrix and set type=Gram </code></pre>
</div>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># We round the loading values for PC1 &amp; PC2 but we extract it before using $loadings</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">print</span>(<span class="fu">round</span>(spca_result<span class="sc">$</span>loadings, <span class="dv">1</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>       PC1  PC2
 [1,]  0.0 -0.5
 [2,]  0.0 -0.5
 [3,]  0.0 -0.5
 [4,]  0.0 -0.5
 [5,] -0.5  0.0
 [6,] -0.5  0.0
 [7,] -0.5  0.0
 [8,] -0.4  0.0
 [9,]  0.0  0.0
[10,]  0.0  0.0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Total variance is explained by SPCA using $pev</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>spca_variance_explained <span class="ot">&lt;-</span> spca_result<span class="sc">$</span>pev <span class="sc">*</span> <span class="dv">100</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="co"># We construct a table using knitr</span></span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-6"><a href="#cb8-6" aria-hidden="true" tabindex="-1"></a><span class="co"># We use PCA and SPCA loadings table using tibble</span></span>
<span id="cb8-7"><a href="#cb8-7" aria-hidden="true" tabindex="-1"></a>loadings_table <span class="ot">&lt;-</span> tibble<span class="sc">::</span><span class="fu">tibble</span>(</span>
<span id="cb8-8"><a href="#cb8-8" aria-hidden="true" tabindex="-1"></a>  <span class="at">Variable =</span> <span class="fu">paste0</span>(<span class="st">"X"</span>, <span class="dv">1</span><span class="sc">:</span><span class="dv">10</span>),</span>
<span id="cb8-9"><a href="#cb8-9" aria-hidden="true" tabindex="-1"></a>  <span class="st">'PCA PC1'</span> <span class="ot">=</span> <span class="fu">round</span>(pca_loading_value<span class="sc">$</span>rotation[, <span class="dv">1</span>], <span class="dv">3</span>),</span>
<span id="cb8-10"><a href="#cb8-10" aria-hidden="true" tabindex="-1"></a>  <span class="st">'PCA PC2'</span> <span class="ot">=</span> <span class="fu">round</span>(pca_loading_value<span class="sc">$</span>rotation[, <span class="dv">2</span>], <span class="dv">3</span>),</span>
<span id="cb8-11"><a href="#cb8-11" aria-hidden="true" tabindex="-1"></a>  <span class="st">'PCA PC3'</span> <span class="ot">=</span> <span class="fu">round</span>(pca_loading_value<span class="sc">$</span>rotation[, <span class="dv">3</span>], <span class="dv">3</span>),</span>
<span id="cb8-12"><a href="#cb8-12" aria-hidden="true" tabindex="-1"></a>  <span class="st">'SPCA PC1'</span> <span class="ot">=</span> <span class="fu">round</span>(spca_result<span class="sc">$</span>loadings[, <span class="dv">1</span>], <span class="dv">1</span>),</span>
<span id="cb8-13"><a href="#cb8-13" aria-hidden="true" tabindex="-1"></a>  <span class="st">'SPCA PC2'</span> <span class="ot">=</span> <span class="fu">round</span>(spca_result<span class="sc">$</span>loadings[, <span class="dv">2</span>], <span class="dv">1</span>)</span>
<span id="cb8-14"><a href="#cb8-14" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-15"><a href="#cb8-15" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-16"><a href="#cb8-16" aria-hidden="true" tabindex="-1"></a><span class="co"># 2. Explained variance table using tibble</span></span>
<span id="cb8-17"><a href="#cb8-17" aria-hidden="true" tabindex="-1"></a>pca_spca_explained_variance <span class="ot">&lt;-</span> tibble<span class="sc">::</span><span class="fu">tibble</span>(</span>
<span id="cb8-18"><a href="#cb8-18" aria-hidden="true" tabindex="-1"></a>  <span class="at">Variable =</span> <span class="st">"Explained Variance (%)"</span>,</span>
<span id="cb8-19"><a href="#cb8-19" aria-hidden="true" tabindex="-1"></a>  <span class="st">'PCA PC1'</span> <span class="ot">=</span> <span class="fu">round</span>(total_explained_variance[<span class="dv">1</span>], <span class="dv">1</span>),</span>
<span id="cb8-20"><a href="#cb8-20" aria-hidden="true" tabindex="-1"></a>  <span class="st">'PCA PC2'</span> <span class="ot">=</span> <span class="fu">round</span>(total_explained_variance[<span class="dv">2</span>], <span class="dv">1</span>),</span>
<span id="cb8-21"><a href="#cb8-21" aria-hidden="true" tabindex="-1"></a>  <span class="st">'PCA PC3'</span> <span class="ot">=</span> <span class="fu">round</span>(<span class="fu">summary</span>(pca_loading_value)<span class="sc">$</span>importance[<span class="st">"Proportion of Variance"</span>, <span class="dv">3</span>] <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">2</span>),</span>
<span id="cb8-22"><a href="#cb8-22" aria-hidden="true" tabindex="-1"></a>  <span class="st">'SPCA PC1'</span> <span class="ot">=</span> <span class="fu">round</span>(spca_result<span class="sc">$</span>pev[<span class="dv">1</span>] <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>),</span>
<span id="cb8-23"><a href="#cb8-23" aria-hidden="true" tabindex="-1"></a>  <span class="st">'SPCA PC2'</span> <span class="ot">=</span> <span class="fu">round</span>(spca_result<span class="sc">$</span>pev[<span class="dv">2</span>] <span class="sc">*</span> <span class="dv">100</span>, <span class="dv">1</span>)</span>
<span id="cb8-24"><a href="#cb8-24" aria-hidden="true" tabindex="-1"></a>)</span>
<span id="cb8-25"><a href="#cb8-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-26"><a href="#cb8-26" aria-hidden="true" tabindex="-1"></a><span class="co"># we combine two table using bind_rows</span></span>
<span id="cb8-27"><a href="#cb8-27" aria-hidden="true" tabindex="-1"></a>result_table <span class="ot">&lt;-</span> <span class="fu">bind_rows</span>(loadings_table, pca_spca_explained_variance)</span>
<span id="cb8-28"><a href="#cb8-28" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-29"><a href="#cb8-29" aria-hidden="true" tabindex="-1"></a><span class="co"># We print the Table for paper.qmd</span></span>
<span id="cb8-30"><a href="#cb8-30" aria-hidden="true" tabindex="-1"></a><span class="fu">kable</span>(result_table, <span class="at">caption =</span> <span class="st">"Table 1: Results of the Simulation Example — Loadings and Variance"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Table 1: Results of the Simulation Example — Loadings and Variance</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Variable</th>
<th style="text-align: right;">PCA PC1</th>
<th style="text-align: right;">PCA PC2</th>
<th style="text-align: right;">PCA PC3</th>
<th style="text-align: right;">SPCA PC1</th>
<th style="text-align: right;">SPCA PC2</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">X1</td>
<td style="text-align: right;">0.118</td>
<td style="text-align: right;">-0.478</td>
<td style="text-align: right;">0.085</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">-0.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">X2</td>
<td style="text-align: right;">0.118</td>
<td style="text-align: right;">-0.478</td>
<td style="text-align: right;">0.092</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">-0.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">X3</td>
<td style="text-align: right;">0.117</td>
<td style="text-align: right;">-0.478</td>
<td style="text-align: right;">0.095</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">-0.5</td>
</tr>
<tr class="even">
<td style="text-align: left;">X4</td>
<td style="text-align: right;">0.118</td>
<td style="text-align: right;">-0.478</td>
<td style="text-align: right;">0.078</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">-0.5</td>
</tr>
<tr class="odd">
<td style="text-align: left;">X5</td>
<td style="text-align: right;">-0.391</td>
<td style="text-align: right;">-0.146</td>
<td style="text-align: right;">-0.266</td>
<td style="text-align: right;">-0.5</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">X6</td>
<td style="text-align: right;">-0.391</td>
<td style="text-align: right;">-0.146</td>
<td style="text-align: right;">-0.263</td>
<td style="text-align: right;">-0.5</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">X7</td>
<td style="text-align: right;">-0.391</td>
<td style="text-align: right;">-0.146</td>
<td style="text-align: right;">-0.274</td>
<td style="text-align: right;">-0.5</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">X8</td>
<td style="text-align: right;">-0.391</td>
<td style="text-align: right;">-0.147</td>
<td style="text-align: right;">-0.298</td>
<td style="text-align: right;">-0.4</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">X9</td>
<td style="text-align: right;">-0.409</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: right;">0.573</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="even">
<td style="text-align: left;">X10</td>
<td style="text-align: right;">-0.409</td>
<td style="text-align: right;">0.005</td>
<td style="text-align: right;">0.580</td>
<td style="text-align: right;">0.0</td>
<td style="text-align: right;">0.0</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Explained Variance (%)</td>
<td style="text-align: right;">59.700</td>
<td style="text-align: right;">40.000</td>
<td style="text-align: right;">0.080</td>
<td style="text-align: right;">39.6</td>
<td style="text-align: right;">39.8</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="sec-6" class="level1" data-number="7">




</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">7 References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-ralexandertellingstorieswithdata" class="csl-entry" role="listitem">
Alexander, Rohan. 2023. <em>Telling Stories with Data: With Applications in r</em>. Boca Raton, FL: Chapman &amp; Hall/CRC Press.
</div>
<div id="ref-R" class="csl-entry" role="listitem">
R Core Team. 2022. <em>R: A Language and Environment for Statistical Computing</em>. Vienna, Austria: R Foundation for Statistical Computing. <a href="https://www.R-project.org/">https://www.R-project.org/</a>.
</div>
<div id="ref-rscalefunction" class="csl-entry" role="listitem">
R-bloggers. 2021. <span>“How to Use the Scale() Function in r.”</span> <a href="https://www.r-bloggers.com/2021/12/how-to-use-the-scale-function-in-r/" class="uri">https://www.r-bloggers.com/2021/12/how-to-use-the-scale-function-in-r/</a>.
</div>
<div id="ref-rPCA" class="csl-entry" role="listitem">
Verzani, John. 2022. <span>“Functions for Principal Component Analysis.”</span> <a href="https://cran.r-project.org/web/packages/LearnPCA/vignettes/Vig_07_Functions_PCA.pdf" class="uri">https://cran.r-project.org/web/packages/LearnPCA/vignettes/Vig_07_Functions_PCA.pdf</a>.
</div>
<div id="ref-rTidyverse" class="csl-entry" role="listitem">
Wickham, Hadley, Mara Averick, Jennifer Bryan, Winston Chang, Lucy D’Agostino McGowan, Romain François, Garrett Grolemund, et al. 2019. <span>“Welcome to the <span class="nocase">tidyverse</span>.”</span> <em>Journal of Open Source Software</em> 4 (43): 1686. <a href="https://doi.org/10.21105/joss.01686">https://doi.org/10.21105/joss.01686</a>.
</div>
<div id="ref-rDplyr" class="csl-entry" role="listitem">
Wickham, Hadley, Romain François, Lionel Henry, and Kirill Müller. 2022. <em>Dplyr: A Grammar of Data Manipulation</em>. <a href="https://CRAN.R-project.org/package=dplyr">https://CRAN.R-project.org/package=dplyr</a>.
</div>
<div id="ref-rKnitr" class="csl-entry" role="listitem">
Xie, Yihui. 2014. <span>“Knitr: A Comprehensive Tool for Reproducible Research in <span>R</span>.”</span> In <em>Implementing Reproducible Computational Research</em>, edited by Victoria Stodden, Friedrich Leisch, and Roger D. Peng. Chapman; Hall/CRC. <a href="http://www.crcpress.com/product/isbn/9781466561595">http://www.crcpress.com/product/isbn/9781466561595</a>.
</div>
<div id="ref-relasticnet" class="csl-entry" role="listitem">
Zou, Hui, and Trevor Hastie. 2020. <em>Elasticnet: Elastic-Net for Sparse Estimation and Sparse PCA</em>. <a href="https://CRAN.R-project.org/package=elasticnet">https://CRAN.R-project.org/package=elasticnet</a>.
</div>
<div id="ref-rSpca" class="csl-entry" role="listitem">
Zou, Hui, Trevor Hastie, and Robert Tibshirani. 2006. <span>“Sparse Principal Component Analysis.”</span> <em>Journal of Computational and Graphical Statistics</em>. <a href="https://doi.org/10.1198/106186006X113430">https://doi.org/10.1198/106186006X113430</a>.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
      &nbsp;
    </div>   
    <div class="nav-footer-center">
      &nbsp;
    </div>
    <div class="nav-footer-right">
      <ul class="footer-items list-unstyled">
    <li class="nav-item">
    <a class="nav-link" href="../about.html">
<p>About me</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="../license.qmd">
<p>License</p>
</a>
  </li>  
    <li class="nav-item">
    <a class="nav-link" href="../trademark.qmd">
<p>Trademark</p>
</a>
  </li>  
</ul>
    </div>
  </div>
</footer>




</body></html>